server:
  port: 7000

spring:
  application:
    name: brokerA
  datasource:
    url: jdbc:mysql://localhost:3307/kevin_mq?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

